# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_engine_app', '0004_auto_20171208_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(upload_to='hotels/cover/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='region',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
